"""
Database models and schema for the trading platform.
"""
from datetime import datetime
from typing import Optional, List
from sqlalchemy import Column, Integer, String, Float, DateTime, Boolean, JSON, ForeignKey, Enum
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
import enum

Base = declarative_base()


class OrderStatus(enum.Enum):
    """Order status enumeration."""
    PENDING = "pending"
    FILLED = "filled"
    PARTIALLY_FILLED = "partially_filled"
    CANCELLED = "cancelled"
    REJECTED = "rejected"


class OrderSide(enum.Enum):
    """Order side enumeration."""
    BUY = "buy"
    SELL = "sell"


class Strategy(Base):
    """Trading strategy model."""
    __tablename__ = "strategies"
    
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, unique=True, nullable=False)
    description = Column(String)
    strategy_type = Column(String)  # ml_based, statistical, hybrid, llm_powered
    parameters = Column(JSON)
    is_active = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Performance metrics
    total_pnl = Column(Float, default=0.0)
    win_rate = Column(Float, default=0.0)
    sharpe_ratio = Column(Float, default=0.0)
    max_drawdown = Column(Float, default=0.0)
    
    # Relationships
    positions = relationship("Position", back_populates="strategy")
    orders = relationship("Order", back_populates="strategy")
    signals = relationship("Signal", back_populates="strategy")


class Position(Base):
    """Current portfolio positions."""
    __tablename__ = "positions"
    
    id = Column(Integer, primary_key=True, index=True)
    strategy_id = Column(Integer, ForeignKey("strategies.id"))
    symbol = Column(String, nullable=False)
    quantity = Column(Float, nullable=False)
    entry_price = Column(Float, nullable=False)
    current_price = Column(Float)
    unrealized_pnl = Column(Float, default=0.0)
    realized_pnl = Column(Float, default=0.0)
    opened_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    strategy = relationship("Strategy", back_populates="positions")


class Order(Base):
    """Order history and tracking."""
    __tablename__ = "orders"
    
    id = Column(Integer, primary_key=True, index=True)
    strategy_id = Column(Integer, ForeignKey("strategies.id"))
    symbol = Column(String, nullable=False)
    side = Column(Enum(OrderSide), nullable=False)
    quantity = Column(Float, nullable=False)
    order_type = Column(String)  # market, limit, stop_loss
    limit_price = Column(Float)
    status = Column(Enum(OrderStatus), default=OrderStatus.PENDING)
    filled_quantity = Column(Float, default=0.0)
    filled_price = Column(Float)
    commission = Column(Float, default=0.0)
    created_at = Column(DateTime, default=datetime.utcnow)
    filled_at = Column(DateTime)
    
    # Relationships
    strategy = relationship("Strategy", back_populates="orders")


class Signal(Base):
    """Trading signals generated by strategies."""
    __tablename__ = "signals"
    
    id = Column(Integer, primary_key=True, index=True)
    strategy_id = Column(Integer, ForeignKey("strategies.id"))
    symbol = Column(String, nullable=False)
    signal_type = Column(String)  # buy, sell, hold
    confidence = Column(Float)  # 0-1 confidence score
    price = Column(Float)
    features = Column(JSON)  # Feature values used for prediction
    created_at = Column(DateTime, default=datetime.utcnow)
    executed = Column(Boolean, default=False)
    
    # Relationships
    strategy = relationship("Strategy", back_populates="signals")


class MarketData(Base):
    """Historical and real-time market data."""
    __tablename__ = "market_data"
    
    id = Column(Integer, primary_key=True, index=True)
    symbol = Column(String, nullable=False, index=True)
    timestamp = Column(DateTime, nullable=False, index=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    close = Column(Float)
    volume = Column(Float)
    timeframe = Column(String)  # 1m, 5m, 1h, 1d


class PerformanceMetrics(Base):
    """Strategy performance tracking over time."""
    __tablename__ = "performance_metrics"
    
    id = Column(Integer, primary_key=True, index=True)
    strategy_id = Column(Integer, ForeignKey("strategies.id"))
    timestamp = Column(DateTime, default=datetime.utcnow)
    total_value = Column(Float)
    cash = Column(Float)
    positions_value = Column(Float)
    daily_pnl = Column(Float)
    cumulative_pnl = Column(Float)
    num_trades = Column(Integer)
    win_rate = Column(Float)
    sharpe_ratio = Column(Float)
    max_drawdown = Column(Float)
